---
- name: Configure MariaDB server
  hosts: infracoston
  gather_facts: no

  tasks:
    - name: Create a new database
      mysql_db:
        name: "{{ mariadb_database }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create a new database user
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Apply privileges
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock